### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by creynders** [GeppettoJS/backbone.geppetto#69]
So maybe it's time to set up a roadmap for v1.0?

What's on my wishlist for Geppetto:
## v0.7.2
- [ ] allow **full wiring configuration** of lazily instantiated components **through the `wire*` methods**. ATM it's only possible to pass an object containing wiring, but I'd like to extend this to include `contextEvents`
- [x] #79 allow wiring an object to multiple keys at once with `wire*(['a', 'b'], Foo);`
- [x] #77 add `wireFactory`
## v0.8
- [ ] **review exceptions** and make them uniform, ATM some are plain strings and some are `Error`s 
- [ ] #74 **drop `bindContext`**. I don't think it's necessary any more ? Or move it to an instance method. Or dissolve it into view constructors or so.
- [ ] speaking of events, **is the `target` parameter in `listen` _really_ necessary**?
- [ ] #76 **logo**
- [ ] `Backbone.migrate` module for backwards compatibility and migration of existing applications to Geppetto.
## Backlog
- [ ] introduce the possibility to do the other way around, translate component-specific events to context events (e.g. `submit:clicked` to `views:login:requested`) This will allow for _completely_ dumb views, since they won't even have to call `dispatch` any more.
- [ ] **promises integration** (which one(s) though?)
- [ ] **expand debugging**. I'd like to investigate a logger approach which logs everything by default, but can easily be turned off (using a null logger?)
- [ ] **figure out a strategy for extensibility**
- [ ] **Refactor tests** and split into several unit and functional tests.
- [ ] **use [must](https://github.com/moll/js-must)** instead of chai, since it's better and cleaner
- [ ] **documentation needs updating!**
- [ ] **port todomvc.geppetto to tastejs**
